
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    # user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      include /etc/nginx/conf.d/*.conf;
      server {
        listen       8765;
        server_name  localhost;
        location / {
          root   /usr/share/nginx/html; #Change this line
          index  index.html index.htm;
        }

        # location /api/customer/ {
        #   proxy_pass http://customers:8282/api/customer/;
        # }
        # location /api/vendor/ {
        #   proxy_pass http://vendors:8383/api/vendor/;
        # }

        location /seznam {
          proxy_pass http://www.seznam.cz/;
        }
      }

    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nginx: "nginx1-instrumentation"
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
        # command: ["sleep", "3600"]
        ports:
        - containerPort: 8765
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 100Mi
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8765
    protocol: TCP
    targetPort: 8765
  selector:
    app: nginx 