apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    load_module /opt/opentelemetry-webserver/agent/WebServerModule/Nginx/1.24.0/ngx_http_opentelemetry_module.so;
    # ^^^^^ needs to be inserted here - this is the OpenTelemetry agent module ^^^^^
    # user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      include /etc/nginx/conf.d/*.conf;
      include /opt/opentelemetry-webserver/agent/nginx-config/otel.conf;
      # ^^^^^ must include /opt/opentelemetry-webserver/agent/nginx-config/otel.conf ^^^^^
      # it contains configuration of OpenTelemetry collector and metadata for AppDynamics
      server {
        listen       8765;
        server_name  localhost;
        location / {
          root   /usr/share/nginx/html; #Change this line
          index  index.html index.htm;
        }

        # location /api/customer/ {
        #   proxy_pass http://customers:8282/api/customer/;
        # }
        # location /api/vendor/ {
        #   proxy_pass http://vendors:8383/api/vendor/;
        # }

        location /seznam {
          proxy_pass http://www.seznam.cz/;
        }
      }

    }

---