apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-conf
data:
  otel.conf: |
    NginxModuleEnabled ON;
    NginxModuleOtelExporterEndpoint http://appdynamics-custom-collector:4317;
    NginxModuleOtelSpanExporter otlp;
    NginxModuleResolveBackends ON;
    NginxModuleServiceInstanceId <<K8S_POD_NAME>>;
    NginxModuleServiceName <<K8S_DEPLOYMENT_NAME>>;
    NginxModuleServiceNamespace <<K8S_POD_NAMESPACE>>;
    NginxModuleTraceAsError ON;

---
